[tox]
envlist = py{310,311}-django-52,py{312,313,314}-django{52,60}, flake8

[travis]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 otp_u2f

[testenv]
allowlist_externals =
    ./manage.py
    pytest
deps =
    django52: django~=5.2.17
    django60: django~=6.0.8
extras =
    dev
    kleides-mfa
setenv =
    PYTHONPATH = {toxinidir}
    PYTHONDONTWRITEBYTECODE=1
    DJANGO_SETTINGS_MODULE=tests.settings
commands =
    ./manage.py check
    pytest --cov --cov-config tox.ini --cov-report term-missing:skip-covered --no-cov-on-fail --nomigrations {posargs}

[coverage:run]
branch = True
source = otp_u2f
omit =
    otp_u2f/migrations/*
    tests/*

[coverage:report]
exclude_lines =
    pragma: no cover

[flake8]
exclude =
    otp_u2f/migrations/*
max-complexity=8
ignore=E121,E123,E126,E226,E24,E704,W503
select=E,F,W,C

[pytest]
# Filter warnings from u2f_host package.
filterwarnings =
    ignore:signer and verifier have been deprecated*:cryptography.utils.CryptographyDeprecationWarning
