# Generated by Django 2.2.6 on 2019-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_u2f', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='u2fdevice',
            name='certificate',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
