# Generated by Django 5.1 on 2026-08-12 13:20

from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Concat, Length, Mod, Substr


def forward_remove_base64_padding(apps, schema_editor):
    U2fDevice = apps.get_model('otp_u2f', 'U2fDevice')
    U2fDevice.objects.filter(credential__endswith='===').update(
        credential=Substr('credential', 1, Length('credential') - 3))
    U2fDevice.objects.filter(credential__endswith='==').update(
        credential=Substr('credential', 1, Length('credential') - 2))
    U2fDevice.objects.filter(credential__endswith='=').update(
        credential=Substr('credential', 1, Length('credential') - 1))
    U2fDevice.objects.filter(public_key__endswith='===').update(
        public_key=Substr('public_key', 1, Length('public_key') - 3))
    U2fDevice.objects.filter(public_key__endswith='==').update(
        public_key=Substr('public_key', 1, Length('public_key') - 2))
    U2fDevice.objects.filter(public_key__endswith='=').update(
        public_key=Substr('public_key', 1, Length('public_key') - 1))


def backward_add_base64_padding(apps, schema_editor):
    U2fDevice = apps.get_model('otp_u2f', 'U2fDevice')
    credential_qs = U2fDevice.objects.annotate(
        padding=Value(4) - Mod(Length('credential'), Value(4))
    )
    credential_qs.filter(padding=1).update(
        credential=Concat(F('credential'), Value('=')))
    credential_qs.filter(padding=2).update(
        credential=Concat(F('credential'), Value('==')))
    credential_qs.filter(padding=3).update(
        credential=Concat(F('credential'), Value('===')))

    public_key_qs = U2fDevice.objects.annotate(
        padding=Value(4) - Mod(Length('public_key'), Value(4))
    )
    public_key_qs.filter(padding=1).update(
        public_key=Concat(F('public_key'), Value('=')))
    public_key_qs.filter(padding=2).update(
        public_key=Concat(F('public_key'), Value('==')))
    public_key_qs.filter(padding=3).update(
        public_key=Concat(F('public_key'), Value('===')))


class Migration(migrations.Migration):

    dependencies = [
        ('otp_u2f', '0002_webauthn'),
    ]

    operations = [
        migrations.RunPython(
            forward_remove_base64_padding,
            backward_add_base64_padding),
    ]
