# Generated by Django 2.2.6 on 2019-10-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_u2f', '0002_u2fdevice_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='u2fdevice',
            name='throttling_failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.'),
        ),
        migrations.AddField(
            model_name='u2fdevice',
            name='throttling_failure_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True),
        ),
    ]
